### ISSUE TITLE
Question:  Any plans to turn this into an Airflow operator?

### ISSUE THREAD

**Issue by cdabel** [datahappy1/mssql_to_redshift_data_transfer_tool#16]

**Comment by Pprud** [comment]
Hi @cdabel I missed your comment completely, Sorry . I think it should be doable let me get back to you in few days .

**Comment by datahappy1** [comment]
hi @cdabel I don't plan to turn this into Airflow operator. Feel free to pick up the torch in here, I can try to help with whatever might be needed. thanks
